---
- name: Get ARP info
  hosts: all
  gather_facts: false

  tasks:
    - name: Run show arp command
      raw: "show arp"
      register: arp_op

    - name: Print arp output to stdout
      debug: var=arp_op.output_lines