---
- name: manage gns3 devices
  hosts: R1
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_become: yes
    ansible_connection: network_cli
    ansible_user: faizan
  tasks:
    - name: enable ospf
      cisco.ios.ios_config:
        parents: router ospf 1
        lines:
          - name: network 0.0.0.0 255.255.255.255 area 0
      register: ospf_op

    - debug: var=ospf_op.stdout_lines