---
- name: Get MAC Table
  hosts: all
  gather_facts: false

  tasks:
    - name: Run show mac address table
      raw: "show mac address-table"
      register: arp_op

    - name: Print arp output to stdout
      debug: var=arp_op.stdout_lines